project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from project_tracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('tasks/', include('tasks.urls')),
    path('', views.index),
    path('tasks/', include('tasks.urls')),
    path('q/', include('quality_control.urls')),
]

quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    #path('', views.index),
    path('', views.IndexView.as_view(), name='index'),

    #path('bugs/', views.bugs_list, name='bugs_list'),
    path('bugs/', views.BugListView.as_view(), name='bugs_list'),

    #path('requests/', views.features_list, name='features_list'),
    path('requests/', views.FeatureListView.as_view(), name='features_list'),

    #path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
    path('bugs/<int:bug_id>/', views.BugDetailView.as_view(), name='bug_detail'),

    #path('requests/<int:feature_id>/', views.feature_detail, name='feature_detail')
    path('requests/<int:feature_id>/', views.FeatureDetailView.as_view(), name='feature_detail'),

    #path('bug/new/', views.create_bugreport, name='create_bugreport'),
    path('bug/new/', views.BugReportCreateView.as_view(), name='create_bugreport'),
    #path('featurerequest/new/', views.create_featurerequest, name='create_featurerequest'),
    path('featurerequest/new/', views.FeatureRequestCreateView.as_view(), name='create_featurerequest'),

    #path('bugs/<int:bug_id>/update/', views.update_bugreport, name='update_bugreport'),
    path('bugs/<int:bug_id>/update/', views.BugReportUpdateView.as_view(), name='update_bugreport'),
    #path('requests/<int:feature_id>/update/', views.update_featurerequest, name='update_featurerequest'),
    path('requests/<int:feature_id>/update/', views.FeatureRequestUpdateView.as_view(), name='update_featurerequest'),

    #path('bugs/<int:bug_id>/delete/', views.delete_bugreport, name='delete_bugreport'),
    path('bugs/<int:bug_id>/delete/', views.BugReportDeleteView.as_view(), name='delete_bugreport'),
    #path('requests/<int:feature_id>/delete/', views.delete_featurerequest, name='delete_featurerequest'),
    path('requests/<int:feature_id>/delete/', views.FeatureRequestDeleteView.as_view(), name='delete_featurerequest'),
]

tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    #path('', views.index),
    #path('projects/', views.projects_list, name='projects_list'),
    #path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    #path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail')
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('project/new/', views.create_project, name='create_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/task/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/task/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task')
]

quality_control/models.py
from tasks.models import Project, Task
from django.db import models

class BugReport(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новый'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершен'),
    ]
    
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        #related_name='bugs',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    priority = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    

class FeatureRequest(models.Model):
    STATUS_CHOICES = [
        ('Review', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено'),
    ]
    
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        #related_name='bugs',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='Review',
    )
    priority = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)    

quality_control/forms.py
from django.forms import ModelForm
from .models import BugReport, FeatureRequest

class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

quality_control/views.py
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from .models import BugReport, FeatureRequest
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import DetailView, View, ListView, CreateView, UpdateView, DeleteView
from .forms import BugReportForm, FeatureRequestForm

def index(request):
    return render(request, 'quality_control/index.html')

def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bug': bug})

def feature_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature})

def bugs_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bugs_list.html', {'bugs_list': bugs})

def features_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/features_list.html', {'features_list': features})

class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')
    
class BugListView(ListView):
    model = BugReport
    context_object_name = 'bugs_list'
    template_name = 'quality_control/bugs_list.html'

class FeatureListView(ListView):
    model = FeatureRequest
    context_object_name = 'features_list'
    template_name = 'quality_control/features_list.html'

class BugDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    context_object_name = 'bug'
    template_name = 'quality_control/bug_detail.html'

class FeatureDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    context_object_name = 'feature'
    template_name = 'quality_control/feature_detail.html'

def create_bugreport(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugs_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})

def create_featurerequest(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:features_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})

def update_bugreport(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug.id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_report_update.html', {'form': form, 'bug': bug})

def update_featurerequest(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', feature_id=feature.id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/bug_report_update.html', {'form': form, 'feature': feature})


def delete_bugreport(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bugs_list')

def delete_featurerequest(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:features_list')


class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control:bugs_list')

class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'
    success_url = reverse_lazy('quality_control:features_list')

class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bugs_list')

class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:features_list')


class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    context_object_name = 'bug'
    success_url = reverse_lazy('quality_control:bugs_list')
    template_name = 'quality_control/bug_report_confirm_delete.html'

class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    context_object_name = 'feature'
    success_url = reverse_lazy('quality_control:features_list')
    template_name = 'quality_control/feature_request_confirm_delete.html'

quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>{{ bug.title }}</h1>
    <p>Описание: {{ bug.description }}</p>
    <p>В проекте: {{ bug.project }}</p>

    <p><a href="{% url 'quality_control:update_bugreport' bug.id %}">Изменить сообщение об ошибке</a></p>

    <p><a href="{% url 'quality_control:delete_bugreport' bug.id %}"onclick="return confirm('Вы уверены, что хотите удалить это сообщение об ошибке?');">Удалить сообщение об ошибке</a></p>
{% endblock %}

quality_control/templates/quality_control/bug_report_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление сообщения об ошибке</h1>
    <p>Вы уверены, что хотите удалить сообщение об ошибке "{{ bug.title }}"?</p>

    <form action="{% url 'quality_control:delete_bugreport' bug.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' bug.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новое сообщение об ошибке</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_report_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение сообщения об ошибке: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bugs_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список багов</h1>

    <!-- Ссылка на создание нового сообщение об ошибке -->
    <p><a href="{% url 'quality_control:create_bugreport' %}">Создать новое сообщение об ошибке</a></p>

    <ul>
        {% for bug in bugs_list %}
            <li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>{{ feature.title }}</h1>
    <p>Описание: {{ feature.description }}</p>
    <p>В проекте: {{ feature.project }}</p>

    <p><a href="{% url 'quality_control:update_featurerequest' feature.id %}">Изменить запрос на улучшение</a></p>

    <p><a href="{% url 'quality_control:delete_featurerequest' feature.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот запрос на улучшение?');">Удалить запрос на улучшение</a></p>

{% endblock %}

quality_control/templates/quality_control/feature_request_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос на улучшение "{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:delete_featurerequest' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail' feature.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новый запрос об улучшении</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_request_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ feature.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/features_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>

    <!-- Ссылка на создание нового запроса на улучшение -->
    <p><a href="{% url 'quality_control:create_featurerequest' %}">Создать новый запрос на улучшение</a></p>
    
    <ul>
        {% for feature in features_list %}
            <li><a href="{% url 'quality_control:feature_detail' feature.id %}">{{ feature.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Страница приложения quality_control</h1>
        <a href="{% url 'quality_control:bugs_list' %}">Список багов</a>
        <p></p>
        <a href="{% url 'quality_control:features_list' %}">Список запросов на улучшение</a>
{% endblock %}